ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.crossprotocolcollateraldrift]
path = "out/CrossProtocolCollateralDriftTrap.sol/CrossProtocolCollateralDriftTrap.json"
response_contract = "response contract address"
response_function = "respond(string,bytes)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["operator address"]
